instance:
  id: 1

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    # The ID of this particular instance of the service.
    instance-id: ${spring.application.name}:${instance.id}

server:
  port: 10000

spring:
  profiles:
    active: default
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9411

security:
  oauth2:
    client:
      client-id: panel-admin-ui
      client-secret: panel-admin-ui-secret
      access-token-uri: http://localhost:9000/services/oauth/token
      user-authorization-uri: http://localhost:9000/services/oauth/authorize
      client-authentication-scheme: form
    resource:
      user-info-uri: http://localhost:9000/services/user
      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
